name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Install testtime
      run: go install github.com/tenntenn/testtime/cmd/testtime@latest

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -overlay=$(go run github.com/tenntenn/testtime/cmd/testtime@latest) ./...

    - name: Run govulncheck
      run: govulncheck ./...